---
deployment:
      tasks:
        - export DEPLOYPATH=/home/u8832552/public_html
        - export PRIVATEPATH=/home/u8832552/private_app
        - /bin/cp -r * $PRIVATEPATH
        - /bin/cp -rf public/* $DEPLOYPATH