export default {
  data () {
    return {
      provinces: [
        {
          id: 0,
          label: "Aceh",
          value: "aceh",
          ongkir: 60000,
        },
        {
          id: 1,
          label: "Sumatera Utara",
          value: "Sumatera Utara",
          ongkir: 45000,
        },
        {
          id: 2,
          label: "Sumatera Barat",
          value: "Sumatera Barat",
          ongkir: 45000,
        },
        {
          id: 3,
          label: "Bali",
          value: "Bali",
          ongkir: 20000,
        },
        {
          id: 4,
          label: "NTB",
          value: "NTB",
          ongkir: 20000,
        },
        {
          id: 5,
          label: "NTT",
          value: "NTT",
          ongkir: 60000,
        },
        {
          id: 6,
          label: "Kalimantan Barat",
          value: "Kalimantan Barat",
          ongkir: 40000,
        },
        {
          id: 7,
          label: "Kalimantan Tengah",
          value: "Kalimantan Tengah",
          ongkir: 50000,
        },
        {
          id: 8,
          label: "Kalimantan Selatan",
          value: "Kalimantan Selatan",
          ongkir: 30000,
        },
        {
          id: 9,
          label: "Kalimantan Timur",
          value: "Kalimantan Timur",
          ongkir: 43000,
        },
        {
          id: 10,
          label: "Kalimantan Utara",
          value: "Kalimantan Utara",
          ongkir: 50000,
        },
        {
          id: 11,
          label: "Sulawesi Utara",
          value: "Sulawesi Utara",
          ongkir: 67000,
        },
        {
          id: 12,
          label: "Gorontalo",
          value: "Gorontalo",
          ongkir: 70000,
        },
        {
          id: 13,
          label: "Sulawesi Tengah",
          value: "Sulawesi Tengah",
          ongkir: 50000,
        },
        {
          id: 14,
          label: "Sulawesi Barat",
          value: "Sulawesi Barat",
          ongkir: 45000,
        },
        {
          id: 15,
          label: "Sulawesi Selatan",
          value: "Sulawesi Selatan",
          ongkir: 40000,
        },
        {
          id: 16,
          label: "Sulawesi Tenggara",
          value: "Sulawesi Tenggara",
          ongkir: 60000,
        },
        {
          id: 17,
          label: "Maluku",
          value: "Maluku_",
          ongkir: 70000,
        },
        {
          id: 18,
          label: "Maluku Utara",
          value: "Maluku Utara",
          ongkir: 70000,
        },
        {
          id: 19,
          label: "Papua Barat",
          value: "Papua Barat",
          ongkir: 145000,
        },
        {
          id: 20,
          label: "Papua",
          value: "Papua_",
          ongkir: 115000,
        },
        {
          id: 21,
          label: "Jawa Timur",
          value: "Jawa Timur",
          ongkir: 10000,
        },
        {
          id: 22,
          label: "Jawa Tengah",
          value: "Jawa Tengah",
          ongkir: 15000,
        },
        {
          id: 23,
          label: "DIY",
          value: "DIY",
          ongkir: 15000,
        },
        {
          id: 24,
          label: "Jakarta",
          value: "Jakarta",
          ongkir: 20000,
        },
        {
          id: 25,
          label: "Jawa Barat",
          value: "Jawa Barat",
          ongkir: 20000,
        },
        {
          id: 26,
          label: "Banten",
          value: "Banten",
          ongkir: 25000,
        },
        {
          id: 27,
          label: "Sumatera Selatan",
          value: "Sumatera Selatan",
          ongkir: 40000,
        },
        {
          id: 28,
          label: "Bangka Belitung",
          value: "Bangka Belitung",
          ongkir: 40000,
        },
        {
          id: 29,
          label: "Jambi",
          value: "Jambi",
          ongkir: 40000,
        },
        {
          id: 30,
          label: "Lampung",
          value: "Lampung",
          ongkir: 40000,
        },
        {
          id: 31,
          label: "Bengkulu",
          value: "Bengkulu",
          ongkir: 45000,
        },
        {
          id: 32,
          label: "Kepulauan Riau",
          value: "Kepulauan Riau",
          ongkir: 50000,
        },
        {
          id: 33,
          label: "Riau",
          value: "Riau_",
          ongkir: 50000,
        },
      ],
    }
  }
}